version: '3.1'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ossp-v3.0
    restart: always
    tty: true
    environment:
      SERVICE_NAME: ossp-v3.0
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: ossp-v3.0-webserver
    restart: always
    tty: true
    ports:
      - "8020:80"
        #  - "4431:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
#  db:
#    image: mysql:8.0.17
#    container_name: laravel8App-db
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    tty: true
#    ports:
#      - "3309:3306"
#    environment:
#      MYSQL_DATABASE: laravel
#      MYSQL_ROOT_PASSWORD: 123456
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    volumes:
#      - dbdata:/var/lib/mysql
#    networks:
#      - app-network
#
  #adminer for db access
#  adminer:
#    image: adminer:latest
#    restart: unless-stopped
#    ports:
#      - 8444:8080

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
#volumes:
#  dbdata:
#    driver: local

