apiVersion: v1
kind: Service
metadata:
  name: $PROJECT_NAME
  namespace: $NAMESPACE
spec:
  ports:
  - name: prp-port
    nodePort: $K8S_NODE_PORT
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: $PROJECT_NAME
  type: NodePort