<?php

return [
    'E_HAJJ_PORTAL' => env('E_HAJJ_PORTAL'),
    'INSIGHTDB_REGISTERED_HAJI_COUNT_URL' => env('INSIGHTDB_REGISTERED_HAJI_COUNT_URL'),
    'INSIGHTDB_PRE_REGISTERED_HAJI_COUNT_URL' => env('INSIGHTDB_PRE_REGISTERED_HAJI_COUNT_URL'),

    'INSIGHTDB_API_CLIENT_ID_PRP' => env('INSIGHTDB_API_CLIENT_ID_PRP'),
    'INSIGHTDB_API_CLIENT_SECRET_PRP' => env('INSIGHTDB_API_CLIENT_SECRET_PRP'),
    'INSIGHTDB_HAJJ_AGENCY_LIST_URL' => env('INSIGHTDB_HAJJ_AGENCY_LIST_URL'),
    'INSIGHTDB_FORM_LIST_URL' => env('INSIGHTDB_FORM_LIST_URL'),

    'INSIGHTDB_API_BASE_URL' => env('INSIGHTDB_API_BASE_URL'),
    'INSIGHTDB_API_TOKEN_URL' => env('INSIGHTDB_API_TOKEN_URL'),
    'INSIGHTDB_API_CLIENT_ID' => env('INSIGHTDB_API_CLIENT_ID'),
    'INSIGHTDB_API_CLIENT_SECRET' => env('INSIGHTDB_API_CLIENT_SECRET'),
    'INSIGHTDB_NEWS_LIST_API_URL' => env('INSIGHTDB_NEWS_LIST_API_URL'),
    'INSIGHTDB_NEWS_LIST_BY_YEAR_API_URL' => env('INSIGHTDB_NEWS_LIST_BY_YEAR_API_URL'),
    'INSIGHTDB_LINK_LIST_URL' => env('INSIGHTDB_LINK_LIST_URL'),

    'EXTERNAL_API_USERNAME' =>  env('EXTERNAL_API_USERNAME'),
    'EXTERNAL_API_PASSWORD' =>  env('EXTERNAL_API_PASSWORD'),
    'EXTERNAL_API_CLIENTID' =>  env('EXTERNAL_API_CLIENTID'),

    'CLIENT_ID' => env('CLIENT_ID'),
    'CLIENT_USER_NAME' => env('CLIENT_USER_NAME'),
    'CLIENT_PASSWORD' => env('CLIENT_PASSWORD'),

    'IDP_CLIENT_SECRET' => env('IDP_CLIENT_SECRET'),
    'IDP_CLIENT_ID' => env('IDP_CLIENT_ID'),
    'EBS_CLIENT_SECRET' => env('EBS_CLIENT_SECRET'),
    'EBS_CLIENT_ID' => env('EBS_CLIENT_ID'),
    'INSIGHTDB_POST_CODE_LIST_URL' => env('INSIGHTDB_POST_CODE_LIST_URL'),
    'NID_REQUEST_API_URL' => env('NID_REQUEST_API_URL'),
    'IDP_TOKEN_API_URL' => env('IDP_TOKEN_API_URL'),


];
